//! `sfmtory init-cam`: estimate camera intrinsics before reconstruction.
//!
//! Every later stage starts from *some* focal length. Without this that value
//! is `1.2 * max(width, height)` - a rule of thumb, roughly a 53-degree
//! horizontal field of view, which is wrong for most cameras and badly wrong
//! for some. Bundle adjustment can refine it later, but only when the scene
//! gives it enough multi-view redundancy to do so; when it doesn't, that
//! initial guess is simply the answer the pipeline reports.
//!
//! No single technique solves this. Each of the estimators below works on a
//! different kind of input and is uninformative outside it, so they run as a
//! cascade and each reports a confidence. Two design rules follow from that,
//! and both matter more than the individual methods:
//!
//! - **Abstaining is a valid result.** A confidently wrong focal length is
//!   worse than the honest heuristic, because it looks like an answer. Every
//!   estimator returns `None` rather than a number it cannot support.
//! - **Independent agreement is evidence.** When two estimators that share no
//!   assumptions land on the same focal, that agreement says more than either
//!   one's own confidence, and is reported.

pub mod exif;
pub mod squares;
pub mod vanishing;

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// How much to trust an estimate. Ordering is meaningful - the cascade keeps
/// the highest-confidence result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Confidence {
    /// Better than nothing, but no real evidence: the field-of-view heuristic.
    Heuristic,
    /// A real measurement whose assumptions may not hold here.
    Low,
    /// A real measurement from data that supports it.
    Medium,
    /// Reported by the camera, or measured from known target geometry.
    High,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Estimate {
    pub method: String,
    pub focal_px: f64,
    pub confidence: Confidence,
    /// Human-readable account of what the estimate was based on.
    pub detail: String,
}

/// What gets written to `cache/init-cam/cameras.toml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitCamResult {
    pub width: u32,
    pub height: u32,
    /// The estimate the cascade selected.
    pub focal_px: f64,
    pub confidence: Confidence,
    pub method: String,
    /// Every estimator that produced an answer, best first.
    pub estimates: Vec<Estimate>,
    /// Present when two independent estimators agreed closely.
    pub agreement: Option<String>,
}

impl InitCamResult {
    /// The `[[cameras]]` stanza to drop into `sfm.toml`.
    pub fn as_camera_toml(&self) -> String {
        format!(
            "# Generated by `sfmtory init-cam` ({}, confidence {:?}).\n\
             # Review before trusting: set `refine = false` only if you are confident.\n\
             [[cameras]]\n\
             name = \"init-cam\"\n\
             images = \"*\"\n\
             model = \"SIMPLE_RADIAL\"\n\
             params = [{:.4}, {:.1}, {:.1}, 0.0]\n",
            self.method,
            self.confidence,
            self.focal_px,
            self.width as f64 / 2.0,
            self.height as f64 / 2.0,
        )
    }
}

/// Two estimates agreeing within this relative margin is treated as corroboration.
const AGREEMENT_TOLERANCE: f64 = 0.10;

/// Runs the cascade over the dataset and picks the best-supported estimate.
///
/// `samples` are `(image bytes, decoded grayscale, width, height)` for a
/// handful of images; `features` are the fiducial detections when the caller
/// has already run `sfmtory feature --detector aruco`.
pub fn run_cascade(
    samples: &[(Vec<u8>, image::GrayImage, u32, u32)],
    features: &[squares::FeatureView<'_>],
) -> Result<InitCamResult> {
    let (w, h) = samples
        .first()
        .map(|(_, _, w, h)| (*w, *h))
        .context("init-cam needs at least one image")?;
    let mut estimates: Vec<Estimate> = Vec::new();

    // Tier 1 - what the camera itself recorded. Exact when present, and
    // present in most photographs that have not been through a messaging app.
    let mut exif_hits = 0usize;
    let mut exif_focals: Vec<f64> = Vec::new();
    let mut exif_desc = String::new();
    for (bytes, _, iw, ih) in samples {
        if let Some(e) = exif::read_jpeg_exif(bytes) {
            if let Some(f) = e.focal_px(*iw, *ih) {
                exif_hits += 1;
                exif_focals.push(f);
                if exif_desc.is_empty() {
                    exif_desc = format!(
                        "{} {} @ {}mm (35mm-equiv)",
                        e.make.unwrap_or_default(),
                        e.model.unwrap_or_default(),
                        e.focal_35mm.unwrap_or_default()
                    )
                    .trim()
                    .to_string();
                }
            }
        }
    }
    if !exif_focals.is_empty() {
        exif_focals.sort_by(|a, b| a.partial_cmp(b).unwrap());
        estimates.push(Estimate {
            method: "exif".into(),
            focal_px: exif_focals[exif_focals.len() / 2],
            confidence: Confidence::High,
            detail: format!(
                "{exif_hits}/{} image(s) carried a 35mm-equivalent focal length; {exif_desc}",
                samples.len()
            ),
        });
    }

    // Tier 2 - fiducial markers are squares, which is known target geometry
    // and therefore a real calibration rather than an inference.
    if !features.is_empty() {
        if let Some(sq) = squares::estimate_focal(features) {
            // Spread across hundreds of independent markers is a direct read
            // on whether the geometry actually constrained the answer.
            let confidence = if sq.relative_spread < 0.08 && sq.num_markers >= 20 {
                Confidence::High
            } else if sq.relative_spread < 0.25 {
                Confidence::Medium
            } else {
                Confidence::Low
            };
            estimates.push(Estimate {
                method: "marker-squares".into(),
                focal_px: sq.focal_px,
                confidence,
                detail: format!(
                    "{} markers -> {} estimates, spread {:.1}% (each ArUco marker is a square, \
                     so its homography is a Zhang calibration constraint)",
                    sq.num_markers,
                    sq.num_estimates,
                    sq.relative_spread * 100.0
                ),
            });
        }
    }

    // Tier 3 - perpendicular structure in the scene itself.
    let mut vp_focals: Vec<f64> = Vec::new();
    let mut vp_pairs = 0usize;
    for (_, gray, _, _) in samples {
        if let Some(v) = vanishing::estimate_focal(gray) {
            vp_focals.push(v.focal_px);
            vp_pairs += v.num_pairs;
        }
    }
    // Require several images to agree closely before this speaks at all.
    //
    // A single image's orthogonality assumption is easy to get wrong - the
    // "vanishing points" found can be accidental concurrences rather than real
    // parallel families, and the resulting focal is then arbitrary rather than
    // merely imprecise. Measured on architectural photos with known ground
    // truth (`sceaux_castle`, true focal 2906px), a loose version of this
    // estimator reported 949px with 31% spread across images. Cross-image
    // agreement is the only cheap signal that separates the two cases, so
    // disagreement is treated as "cannot answer" rather than as a low-quality
    // answer that would still outrank the heuristic.
    const VP_MAX_SPREAD: f64 = 0.15;
    const VP_MIN_IMAGES: usize = 3;
    if vp_focals.len() >= VP_MIN_IMAGES {
        vp_focals.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let median = vp_focals[vp_focals.len() / 2];
        let mut devs: Vec<f64> = vp_focals.iter().map(|f| (f - median).abs()).collect();
        devs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let spread = devs[devs.len() / 2] / median;
        if spread <= VP_MAX_SPREAD {
        estimates.push(Estimate {
            method: "vanishing-points".into(),
            focal_px: median,
            // Agreement *across images* is what makes this trustworthy: one
            // image's orthogonality assumption can be wrong, several images
            // being wrong the same way is far less likely.
            confidence: if vp_focals.len() >= 4 && spread < 0.15 {
                Confidence::Medium
            } else {
                Confidence::Low
            },
            detail: format!(
                "{} image(s) yielded orthogonal vanishing-point pairs ({vp_pairs} pairs total), \
                 spread {:.1}%",
                vp_focals.len(),
                spread * 100.0
            ),
        });
        }
    }

    // The existing rule of thumb, always present so there is a defined answer.
    estimates.push(Estimate {
        method: "fov-heuristic".into(),
        focal_px: w.max(h) as f64 * 1.2,
        confidence: Confidence::Heuristic,
        detail: "1.2 x longest image side (~53 degree horizontal field of view)".into(),
    });

    estimates.sort_by_key(|e| std::cmp::Reverse(e.confidence));
    let best = estimates[0].clone();

    // Corroboration between estimators that share no assumptions.
    let mut agreement = None;
    for other in estimates.iter().skip(1) {
        if other.confidence == Confidence::Heuristic {
            continue;
        }
        let rel = (other.focal_px - best.focal_px).abs() / best.focal_px;
        if rel < AGREEMENT_TOLERANCE {
            agreement = Some(format!(
                "`{}` independently agrees within {:.1}%",
                other.method,
                rel * 100.0
            ));
            break;
        }
    }

    Ok(InitCamResult {
        width: w,
        height: h,
        focal_px: best.focal_px,
        confidence: best.confidence,
        method: best.method.clone(),
        estimates,
        agreement,
    })
}

pub fn write_result(dir: &Path, result: &InitCamResult) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    let json = dir.join("intrinsics.json");
    std::fs::write(&json, serde_json::to_string_pretty(result)?)
        .with_context(|| format!("writing {}", json.display()))?;
    let toml = dir.join("cameras.toml");
    std::fs::write(&toml, result.as_camera_toml())
        .with_context(|| format!("writing {}", toml.display()))?;
    Ok(())
}
